### ISSUE TITLE
[紧急]packagist not publish

### ISSUE THREAD

**Issue by medz** [overtrue/laravel-subscribe#1]
超哥，这个包还没有在 packagist 发布哦。按照 readme 是查不到这个包的。无法安装

**Comment by hldh214** [comment]
其实蛮好奇的已经有 `laravel-follow` 了为啥还要新开这么多项目

**Comment by medz** [comment]
@hldh214 我最近用 laravel-follow 遇到了挺多坑和这个包的bug 的，拆分成不同的业务包挺好的，只需要其中一个两个就只导入对应的包。

**Comment by overtrue** [comment]
@medz 发布了哈，不好意思

**Comment by overtrue** [comment]
@hldh214 最开始做那个包的时候考虑的场景不够丰富，导致 issue 里部分问题不好解决，所以在大家的建议下分包了。
