### ISSUE TITLE
Get Title from Subscription.

### ISSUE THREAD

**Issue by haleyngonadi** [overtrue/laravel-subscribe#10]
Hello, thanks for the package. I'm having an issue retrieving details about a user's subscriptions. 

`$user = User::whereId(1)->with('subscriptions')->withType->(Movie::class)->first();`
`$title = $user->subscriptions->first()->pluck('movie_title');`
`return $title;`

This returns an error. How do I get details from the subscription then?

**Comment by overtrue** [comment]
please show me the error.

**Comment by overtrue** [comment]
You have a syntax error at:

```diff
- ->withType->(Movie::class)
+ ->withType(Movie::class)
```

**Comment by haleyngonadi** [comment]
Hi, I figured it out: 

$user->subscriptions->first()->pluck('subscribable.movie_title')
