### ISSUE TITLE
issue getting subscriptions

### ISSUE THREAD

**Issue by Elusoji** [overtrue/laravel-subscribe#12]
i want to get thread(post) associated with the space a user has subscribe to

```
 $spaces = Space::whereHas('subscribers', function($query){
            $query->where('subscribable_id', '=', 'user_id');
        })->with('thread')->orderBy('id', 'desc')->paginate(10);

**Comment by Elusoji** [comment]
> 

i was trying to get space a user subscribe to and i checked the subscription table and i use the subscribable_id , the user_id i have change it to auth()->id()

please kindly assist this is only getting one space a user subscribe to and i am trying to do is get all space thread a user is subscribed to

**Comment by overtrue** [comment]
please make a data table example and the result you expected.

**Comment by Elusoji** [comment]
i have a space model and thread model model

space model has relationship with thread model

a user can subscribe to a space

what i wanted to do is when a user subscribe to a space i want to get all thread associated with that space a user subscribe to

so if a user subscribe to 5 space i want to get all threads associated to those space

**Comment by overtrue** [comment]
please take a try:

```php
$threads = Thread::whereHas('space', function($query){
            $query->whereHas('subscribers', fn($q) => $q->where('id', auth()->id()));
        })->latest('threads.id')->paginate(10);
```

**Comment by Elusoji** [comment]
i got this error 
```
Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

**Comment by overtrue** [comment]
```php
$threads = Thread::whereHas('space', function($query){
            $query->whereHas('subscribers', fn($q) => $q->where('users.id', auth()->id()));
        })->latest('threads.id')->paginate(10);
```
