### ISSUE TITLE
User can not subscribe on another user

### ISSUE THREAD

**Issue by romansidorov** [overtrue/laravel-subscribe#6]
Hi!

I have noticed that user can not subscribe on another user because there is a conflict between `subscriptions()` methods in the package traits.

Is it a bug or a feature? :)

**Comment by overtrue** [comment]
Shouldn't this behavior be called "follow"? I made a package to support this feature: https://github.com/overtrue/laravel-follow.

**Comment by overtrue** [comment]
OK，I will create a package after a few days.

发自我的iPhone

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-subscribe/releases/tag/3.0.0 @ersanyakit done.

**Comment by ersanyakit** [comment]
Thank you very much my love❤️❤️❤️❤️

💗💗💗💗💗💗💋💋💋💋💋💋💋💋

**Comment by overtrue** [comment]
@ersanyakit 😆
