### ISSUE TITLE
Unable to get recent subscribers!

### ISSUE THREAD

**Issue by haleyngonadi** [overtrue/laravel-subscribe#8]
I'm trying to get a user's recent subscribers in the last 24 hours and I'm running into an Integrity constraint violation error:

```
$date = Carbon::now();
$from = $date->startofDay()->toIso8601String();
$to = $date->endofDay()->toIso8601String();
$subscribers = $user->subscribers()->whereBetween('created_at', [$from, $to])->count();
```

This returns an error:

  SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous (SQL: select count(*) as aggregate from `users` inner join `followables` on `users`.`id` = `followables`.`user_id` where `followables`.`followable_id` = 2 and `followables`.`followable_type` = App\Models\User and `followables`.`relation` = subscribe and `created_at` between 2021-07-01T00:00:00-04:00 and 2021-07-01T23:59:59-04:00 and `users`.`deleted_at` is null)

**Comment by overtrue** [comment]
Plz take a try:
```php
$user->subscribers()->whereBetween('followables.created_at', [$from, $to])->count();
```

**Comment by haleyngonadi** [comment]
That worked. Thank you!

**Comment by haleyngonadi** [comment]
Hi @overtrue! Since migrating, this no longer works. What do I use now?

**Comment by overtrue** [comment]
@haleyngonadi Please check the diff from 1.1.0-2.0.0 https://github.com/overtrue/laravel-subscribe/compare/1.1.0...2.0.0
There has been no logic change, just upgrade dependency version and UUIDs support.

**Comment by haleyngonadi** [comment]
@overtrue Hey, I"m saying this code you shared  above before no longer works with 2x.

`$user->subscribers()->whereBetween('followables.created_at', [$from, $to])->count();
`

What does this change to in 2x?

**Comment by overtrue** [comment]
@haleyngonadi I find that we seem to have made a confusion: This package has no tables named 'followables' yet: 

https://github.com/overtrue/laravel-subscribe/blob/1.0.0/migrations/2020_04_09_000000_create_subscriptions_table.php#L22

maybe you are using [laravel-follow](https://github.com/overtrue/laravel-follow)?

**Comment by haleyngonadi** [comment]
@overtrue  With this package, can you please tell me how to get the most recently subscribed to? I want to be able to show what Posts are popular.

**Comment by overtrue** [comment]
@haleyngonadi So, the correct answer is:

```php
$todaySubscribedUsers = $user->subscribers()->wherePivotBetween('subscriptions.created_at', [$from, $to])->get();
```

**Comment by overtrue** [comment]
> @overtrue With this package, can you please tell me how to get the most recently subscribed to? I want to be able to show what Posts are popular.

please wait a moment.

**Comment by overtrue** [comment]
> @overtrue With this package, can you please tell me how to get the most recently subscribed to? I want to be able to show what Posts are popular.

1. Order by `subscribers_count`
```php
$postsOrderBySubscribersCount = Post::withCount('subscribers')->orderByDesc('subscribers_count')->get();
```

2. Most popular post:

```php
$mostPopularPost = Post::withCount('subscribers')->orderByDesc('subscribers_count')->first();
```

And I added 3 shortcut methods:

- `orderBySubscribersCountDesc()`
- `orderBySubscribersCountAsc()`
- `orderBySubscribersCount(string $direction = 'desc')`

```php
Post::withCount('subscribers')->orderByDesc('subscribers_count')->get();
// you can write as:
Post::orderBySubscribersCountDesc()->get();
```

**Comment by haleyngonadi** [comment]
Thanks for the help on popular posts. Recently subscribed posts are still not working for me. Can you give it a try?


```
    $dated = Carbon::now();

      $to = $dated->endofDay()->format('Y-m-d H:i:s');
      $from = $dated->subDays(14)->format('Y-m-d H:i:s');
    
    $todaySubscribedUsers = Show::where('status', 'Running')->whereHas('subscribers', function ($q) use ($to, $from) {
        $q->wherePivotBetween('subscriptions.created_at', [$from, $to]);
      })->get();
```

I get the error: 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pivot_between' in 'where clause' (SQL: select `shows`.*, (select count(*) from `users` inner join `subscriptions` on `users`.`id` = `subscriptions`.`user_id` where `shows`.`id` = `subscriptions`.`subscribable_id` and `subscribable_type` = App\Models\Show and `users`.`deleted_at` is null) as `subscribers_count` from `shows` where `status` = Running and exists (select * from `users` inner join `subscriptions` on `users`.`id` = `subscriptions`.`user_id` where `shows`.`id` = `subscriptions`.`subscribable_id` and `pivot_between` = subscriptions.created_at and `subscribable_type` = App\Models\Show and `users`.`deleted_at` is null) order by `subscribers_count` desc limit 20)

**Comment by overtrue** [comment]
plz paste the source of `App\Models\Show`

**Comment by haleyngonadi** [comment]
```
<?php

namespace App\Models;

use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

use Overtrue\LaravelSubscribe\Traits\Subscribable;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class Show extends Model implements HasMedia, TranslatableContract
{

  use Translatable, InteractsWithMedia, Subscribable;

  protected $appends = [
    'poster', 'url'
  ];

  public function seasons()
  {
    return $this->hasMany(Season::class);
  }


  public function episodes()
  {
    return $this->hasMany(Episode::class);
  }
}
```

**Comment by overtrue** [comment]
Please confirm the package version:
```bash
composer info overtrue/laravel-subscribe
```

**Comment by haleyngonadi** [comment]
name     : overtrue/laravel-subscribe
descrip. : User Subscribe/Unsubscribe features for Laravel Application.
keywords : 
versions : * 3.0.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/overtrue/laravel-subscribe.git 020931e6620ab5595673a60642614f9d74d0fdf4
dist     : [zip] https://api.github.com/repos/overtrue/laravel-subscribe/zipball/020931e6620ab5595673a60642614f9d74d0fdf4 020931e6620ab5595673a60642614f9d74d0fdf4
path     : /Users/dalia/Develop/dizilah/vendor/overtrue/laravel-subscribe
names    : overtrue/laravel-subscribe

support
issues : https://github.com/overtrue/laravel-subscribe/issues
source : https://github.com/overtrue/laravel-subscribe/tree/3.0.0

autoload
psr-4
Overtrue\LaravelSubscribe\ => src

requires
laravel/framework ^8.0
php >=7.4

requires (dev)
brainmaestro/composer-git-hooks ^2.7
friendsofphp/php-cs-fixer ^3.0
laravel/framework ^8.12
mockery/mockery ^1.2
orchestra/testbench ^6.0
phpunit/phpunit ^9.0

**Comment by overtrue** [comment]
Plz upgrade to 3.1.0 and try again.

**Comment by haleyngonadi** [comment]
Hey, I just did. I get the same error.  

```
  $dated = Carbon::now();

      $to = $dated->endofDay()->format('Y-m-d H:i:s');
      $from = $dated->subDays(14)->format('Y-m-d H:i:s');
    
    return Show::where('status', 'Running')->whereHas('subscribers', function ($q) use ($to, $from) {
        $q->wherePivotBetween('subscriptions.created_at', [$from, $to]);
      })->with('media')->withCount('subscribers')->orderBy('subscribers_count', 'desc')->take(20)->get();

```

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pivot_between' in 'where clause' (SQL: select `shows`.*, (select count(*) from `users` inner join `subscriptions` on `users`.`id` = `subscriptions`.`user_id` where `shows`.`id` = `subscriptions`.`subscribable_id` and `subscribable_type` = App\Models\Show and `users`.`deleted_at` is null) as `subscribers_count` from `shows` where `status` = Running and exists (select * from `users` inner join `subscriptions` on `users`.`id` = `subscriptions`.`user_id` where `shows`.`id` = `subscriptions`.`subscribable_id` and `pivot_between` = subscriptions.created_at and `subscribable_type` = App\Models\Show and `users`.`deleted_at` is null) order by `subscribers_count` desc limit 20)

**Comment by overtrue** [comment]
```php
      $dated = Carbon::now();

      $to = $dated->endofDay()->format('Y-m-d H:i:s');
      $from = $dated->subDays(14)->format('Y-m-d H:i:s');
    
    return Show::where('status', 'Running')->whereHas('subscribers', function ($q) use ($to, $from) {
        $q->wherePivot('subscriptions.created_at', 'between', [$from, $to]);
      })->with('media')->withCount('subscribers')->orderBy('subscribers_count', 'desc')->take(20)->get();

```

**Comment by haleyngonadi** [comment]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pivot' in 'where clause' (SQL: select `shows`.*, (select count(*) from `users` inner join `subscriptions` on `users`.`id` = `subscriptions`.`user_id` where `shows`.`id` = `subscriptions`.`subscribable_id` and `subscribable_type` = App\Models\Show and `users`.`deleted_at` is null) as `subscribers_count` from `shows` where `status` = Running and exists (select * from `users` inner join `subscriptions` on `users`.`id` = `subscriptions`.`user_id` where `shows`.`id` = `subscriptions`.`subscribable_id` and `pivot` = subscriptions.created_at and `subscribable_type` = App\Models\Show and `users`.`deleted_at` is null) order by `subscribers_count` desc limit 20)

**Comment by overtrue** [comment]
Which version of your Laravel?

**Comment by haleyngonadi** [comment]
Laravel Framework 8.69.0

**Comment by haleyngonadi** [comment]
Hey, I think I just got it working :) 


```
 $dated = Carbon::now();
  $to = $dated->endofDay()->format('Y-m-d H:i:s');
      $from = $dated->subDays(14)->format('Y-m-d H:i:s');
    
    return Show::where('status', 'Running')->whereHas('subscribers', function ($q) use ($to, $from) {
        $q->whereBetween('subscriptions.created_at', [$from, $to]);
      })->with(['media'])->withCount('subscribers')->orderBy('subscribers_count', 'desc')->take(20)->get();
    
```

**Comment by overtrue** [comment]
`wherePivot()` is a member of ManyToMany relationship and not general Query builder, hence scope would not work as expected in this case. 

you can use the `where` method: 

```php
return Show::where('status', 'Running')->whereHas('subscribers', function ($q) use ($to, $from) {
        $q->whereBetween('subscriptions.created_at', 'between', [$from, $to]);
      })->with('media')->withCount('subscribers')->orderBy('subscribers_count', 'desc')->take(20)->get();
```

**Comment by overtrue** [comment]
😆

**Comment by haleyngonadi** [comment]
Thank you so much for all your help! 🎉
